[package]
name = "rusty_v8"
version = "0.0.3"
description = "Rust bindings to V8"
readme = "README.md"
authors = ["the Deno authors"]
license = "MIT"
edition = "2018"
repository = "https://github.com/denoland/rusty_v8"

exclude = [
 # To keep the package under the 10mb limit imposed by crates.io we exclude
 # a lot of files that are not needed for the build.
 "*.md",
 "*.txt",
 "*.py",
 "*OWNERS*",
 "AUTHORS",
 "LICENSE*",
 "README*",
 "build/android/",
 "build/chromeos/",
 "build/fuchsia/",
 "buildtools/third_party/libc++/trunk/test/",
 "buildtools/third_party/libc++abi/trunk/test/",
 "buildtools/checkdeps/",
 "buildtools/clang_format/",
 "v8/*.settings",
 "v8/ChangeLog",
 "v8/docs/",
 "v8/samples/",
 "v8/test/",
 "v8/third_party/wasm-api",
 "v8/tools/",
 # These files are required for the build.
 "!BUILD.gn",
 "!test-torque.tq",
 "!v8/tools/run.py",
 "!v8/tools/testrunner/utils/dump_build_config.py",
 "!v8/tools/gen-postmortem-metadata.py",
 "!v8/tools/js2c.py",
 "!tools/clang/scripts/update.py",
 "!build/mac/should_use_hermetic_xcode.py",
]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.65"

[build-dependencies]
cargo_gn = "0.0.13"
which = "3.0.0"
