[package]
name = "rusty_v8"
version = "0.0.22"
description = "Rust bindings to V8"
readme = "README.md"
authors = ["the Deno authors"]
license = "MIT"
edition = "2018"
repository = "https://github.com/denoland/rusty_v8"

exclude = [
 # To keep the package under the 10mb limit imposed by crates.io we exclude
 # a lot of files that are not needed for the build.
 "*.md",
 "*.settings",
 "*.txt",
 "*OWNERS*",
 "AUTHORS",
 "LICENSE*",
 "README*",
 "build/android/",
 "build/chromeos/",
 "build/fuchsia/",
 "buildtools/checkdeps/",
 "buildtools/clang_format/",
 "buildtools/third_party/libc++/trunk/benchmarks/",
 "buildtools/third_party/libc++/trunk/docs/",
 "buildtools/third_party/libc++/trunk/lib/",
 "buildtools/third_party/libc++/trunk/test/",
 "buildtools/third_party/libc++/trunk/utils/",
 "buildtools/third_party/libc++/trunk/www/",
 "buildtools/third_party/libc++abi/trunk/test/",
 "v8/ChangeLog",
 "v8/benchmarks/",
 "v8/docs/",
 "v8/samples/",
 "v8/test/",
 "v8/tools/profviz",
 "v8/tools/turbolizer",
 "v8/tools/testrunner",
 "v8/tools/release",
 "v8/tools/grokdump.py",
 "v8/tools/mb",
 "v8/tools/unittests",
 "v8/tools/gcmole",
 "v8/tools/clusterfuzz",
 "v8/tools/heap-stats",
 "v8/tools/profview",
 "v8/tools/debug_helper",
 "v8/tools/callstats.html",
 "v8/tools/sanitizers",
 "v8/tools/ignition",
 "v8/third_party/wasm-api/",
 # These files are required for the build.
 "!BUILD.gn",
 "!test-torque.tq",
 "!v8/tools/run.py",
 "!v8/tools/testrunner/utils/dump_build_config.py",
 "!v8/tools/gen-postmortem-metadata.py",
 "!v8/tools/js2c.py",
 "!tools/clang/scripts/update.py",
]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.66"
bitflags = "1.2.1"

[build-dependencies]
cargo_gn = "0.0.15"
which = "3.1.0"

[dev-dependencies]
trybuild = "1.0.19"
